name: Build, Publish & Release Widget

on:
  push:
    tags: ['v*']

env:
  NODE_VERSION: '18'

permissions:
  contents: write  # for creating GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: widget-dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
      - uses: actions/download-artifact@v4
        with:
          name: widget-dist
          path: dist/
      - id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## 🚀 Toratech AI Pop-out Widget v${{ steps.version.outputs.VERSION }}
            
            ### 📦 Installation
            ```html
            <!-- Via jsDelivr CDN (Recommended) -->
            <script src="https://cdn.jsdelivr.net/npm/toratech-popout-widget@${{ steps.version.outputs.VERSION }}/dist/widget.umd.js"></script>
            
            <!-- Latest version via jsDelivr -->
            <script src="https://cdn.jsdelivr.net/npm/toratech-popout-widget@latest/dist/widget.umd.js"></script>
            
            <!-- ES Module version via jsDelivr -->
            <script type="module">
              import MyPopoutWidget from 'https://cdn.jsdelivr.net/npm/toratech-popout-widget@${{ steps.version.outputs.VERSION }}/dist/widget.es.js';
              // Your initialization code here
            </script>
            ```
            
            ### 🎯 Usage
            ```javascript
            MyPopoutWidget.init({
              branding: {
                name: 'Your Support Team',
                welcomeText: 'How can we help you today?'
              }
            });
            ```
            
            ### 📋 Files in this release
            - `widget.min.js` - Main widget JavaScript (minified)
            - `widget.css` - Widget styles (optional, styles are embedded in JS)
            - Source maps for debugging
