name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'dist/**'
      - '.github/workflows/github-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create CDN directory structure
        run: |
          mkdir -p cdn/latest
          mkdir -p cdn/v1.0.0
          cp dist/widget.umd.js cdn/latest/
          cp dist/widget.es.js cdn/latest/
          cp dist/widget.umd.js cdn/v1.0.0/
          cp dist/widget.es.js cdn/v1.0.0/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'cdn'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output CDN URLs
        run: |
          echo "🚀 Widget deployed to GitHub Pages"
          echo "CDN URLs:"
          echo "UMD (latest): https://tora-carl.github.io/popout-chat/latest/widget.umd.js"
          echo "ES Module (latest): https://tora-carl.github.io/popout-chat/latest/widget.es.js"
          echo "UMD (v1.0.0): https://tora-carl.github.io/popout-chat/v1.0.0/widget.umd.js"
          echo "ES Module (v1.0.0): https://tora-carl.github.io/popout-chat/v1.0.0/widget.es.js"
